### ISSUE TITLE
Laggy animation effect

### ISSUE THREAD

**Issue by RD001** [werthdavid/MMM-BurnIn#1]
After first flicker, animation effect of other modules gets laggy.

**Comment by stackrainbow** [comment]
This is due to the use of filter: invert(0) to cancel the inversion.
I think it causes lag because it forces the element to still be considered as having a special effect and therefore there is still some special rendering going on.

I fixed this for myself by editing the following line: https://github.com/werthdavid/MMM-BurnIn/blob/master/MMM-BurnIn.js#L26
change it to
```
document.getElementsByTagName("body").item(0).style = "filter: unset";
```

**Comment by werthdavid** [comment]
Awesome, thanks! Much appreciated
